import type { Category } from '@/types';

export const PLATFORM_FEE_PERCENT = 10;
export const DEFAULT_NEGOTIATION_RADIUS_KM = 30;

export const PHOTO_LABELS = [
  'Frente',
  'Lado Esquerdo',
  'Lado Direito',
  'Traseira',
  'Detalhe 1',
  'Detalhe 2',
  'Contexto',
  'Complementar',
];

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Eletrônicos', icon: '📱', slug: 'eletronicos' },
  { id: '2', name: 'Móveis', icon: '🛋️', slug: 'moveis' },
  { id: '3', name: 'Veículos', icon: '🚗', slug: 'veiculos' },
  { id: '4', name: 'Roupas', icon: '👕', slug: 'roupas' },
  { id: '5', name: 'Esportes', icon: '⚽', slug: 'esportes' },
  { id: '6', name: 'Casa', icon: '🏠', slug: 'casa' },
  { id: '7', name: 'Brinquedos', icon: '🧸', slug: 'brinquedos' },
  { id: '8', name: 'Livros', icon: '📚', slug: 'livros' },
  { id: '9', name: 'Games', icon: '🎮', slug: 'games' },
  { id: '10', name: 'Beleza', icon: '💄', slug: 'beleza' },
  { id: '11', name: 'Ferramentas', icon: '🔧', slug: 'ferramentas' },
  { id: '12', name: 'Outros', icon: '📦', slug: 'outros' },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    user_id: 'u1',
    title: 'iPhone 14 Pro Max 256GB',
    description: 'iPhone em perfeito estado, com caixa e todos os acessórios originais. Bateria 94%.',
    category_id: '1',
    price: 5200,
    condition: 'like_new' as const,
    usage_time: '8 meses',
    location_lat: -23.5505,
    location_lng: -46.6333,
    city: 'São Paulo',
    state: 'SP',
    negotiation_radius_km: 20,
    status: 'active' as const,
    video_status: 'ready' as const,
    video_thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=600&fit=crop',
    allow_resale_by_others: true,
    reseller_commission_type: 'percentage' as const,
    reseller_commission_value: 5,
    donation_enabled: true,
    donation_type: 'percentage' as const,
    donation_value: 2,
    auction_enabled: false,
    flash_offer_enabled: false,
    views_count: 342,
    favorites_count: 28,
    regeneration_count: 0,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'i1', product_id: '1', url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800', position: 0, label: 'Frente', created_at: '' },
      { id: 'i2', product_id: '1', url: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=800', position: 1, label: 'Traseira', created_at: '' },
    ],
    user: { id: 'u1', email: 'maria@email.com', name: 'Maria Santos', type: 'seller' as const, city: 'São Paulo', state: 'SP', created_at: '', is_pro: true },
    category: { id: '1', name: 'Eletrônicos', icon: '📱', slug: 'eletronicos' },
    distance_km: 2.3,
  },
  {
    id: '2',
    user_id: 'u2',
    title: 'Sofá Retrátil 3 Lugares Cinza',
    description: 'Sofá em ótimo estado, tecido suede cinza. Sem manchas. Retrátil e reclinável.',
    category_id: '2',
    price: 1800,
    condition: 'good' as const,
    usage_time: '2 anos',
    location_lat: -23.5605,
    location_lng: -46.6533,
    city: 'São Paulo',
    state: 'SP',
    negotiation_radius_km: 15,
    status: 'active' as const,
    video_status: 'ready' as const,
    video_thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=600&fit=crop',
    allow_resale_by_others: false,
    donation_enabled: false,
    auction_enabled: false,
    flash_offer_enabled: true,
    flash_offer_price: 1500,
    flash_offer_end_at: new Date(Date.now() + 3600000 * 4).toISOString(),
    flash_offer_status: 'active' as const,
    views_count: 156,
    favorites_count: 12,
    regeneration_count: 0,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'i3', product_id: '2', url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', position: 0, label: 'Frente', created_at: '' },
    ],
    user: { id: 'u2', email: 'joao@email.com', name: 'João Silva', type: 'seller' as const, city: 'São Paulo', state: 'SP', created_at: '', is_pro: false },
    category: { id: '2', name: 'Móveis', icon: '🛋️', slug: 'moveis' },
    distance_km: 5.1,
  },
  {
    id: '3',
    user_id: 'u3',
    title: 'Bicicleta Speed Caloi Strada',
    description: 'Bicicleta speed Caloi Strada, quadro alumínio tamanho M, 16 marchas Shimano Claris.',
    category_id: '5',
    price: 2800,
    condition: 'like_new' as const,
    usage_time: '6 meses',
    location_lat: -23.5405,
    location_lng: -46.6433,
    city: 'São Paulo',
    state: 'SP',
    negotiation_radius_km: 30,
    status: 'active' as const,
    video_status: 'processing' as const,
    allow_resale_by_others: true,
    reseller_commission_type: 'percentage' as const,
    reseller_commission_value: 8,
    donation_enabled: true,
    donation_type: 'fixed' as const,
    donation_value: 50,
    charity_id: 'c1',
    auction_enabled: false,
    flash_offer_enabled: false,
    views_count: 89,
    favorites_count: 7,
    regeneration_count: 0,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'i4', product_id: '3', url: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800', position: 0, label: 'Frente', created_at: '' },
    ],
    user: { id: 'u3', email: 'ana@email.com', name: 'Ana Oliveira', type: 'seller' as const, city: 'São Paulo', state: 'SP', created_at: '', is_pro: false },
    category: { id: '5', name: 'Esportes', icon: '⚽', slug: 'esportes' },
    distance_km: 0.8,
  },
  {
    id: '4',
    user_id: 'u4',
    title: 'PlayStation 5 + 2 Controles',
    description: 'PS5 com disco, 2 controles DualSense, cabos e caixa. Pouco uso, sem riscos.',
    category_id: '9',
    price: 3400,
    condition: 'like_new' as const,
    usage_time: '4 meses',
    location_lat: -23.5305,
    location_lng: -46.6233,
    city: 'São Paulo',
    state: 'SP',
    negotiation_radius_km: 25,
    status: 'active' as const,
    video_status: 'ready' as const,
    video_thumbnail: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=600&fit=crop',
    allow_resale_by_others: false,
    donation_enabled: false,
    auction_enabled: true,
    auction_start_price: 2500,
    auction_current_bid: 3100,
    auction_end_at: new Date(Date.now() + 3600000 * 48).toISOString(),
    auction_status: 'open' as const,
    flash_offer_enabled: false,
    views_count: 521,
    favorites_count: 45,
    regeneration_count: 0,
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'i5', product_id: '4', url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800', position: 0, label: 'Frente', created_at: '' },
    ],
    user: { id: 'u4', email: 'pedro@email.com', name: 'Pedro Costa', type: 'seller' as const, city: 'São Paulo', state: 'SP', created_at: '', is_pro: true },
    category: { id: '9', name: 'Games', icon: '🎮', slug: 'games' },
    distance_km: 3.7,
  },
  {
    id: '5',
    user_id: 'u5',
    title: 'MacBook Air M2 2023 Midnight',
    description: 'MacBook Air M2, 8GB RAM, 256GB SSD, cor Midnight. Com AppleCare até 2025.',
    category_id: '1',
    price: 7500,
    condition: 'like_new' as const,
    usage_time: '3 meses',
    location_lat: -23.5705,
    location_lng: -46.6633,
    city: 'São Paulo',
    state: 'SP',
    negotiation_radius_km: 50,
    status: 'active' as const,
    video_status: 'ready' as const,
    video_thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=600&fit=crop',
    allow_resale_by_others: true,
    reseller_commission_type: 'percentage' as const,
    reseller_commission_value: 3,
    donation_enabled: false,
    auction_enabled: false,
    flash_offer_enabled: false,
    views_count: 267,
    favorites_count: 33,
    regeneration_count: 0,
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'i6', product_id: '5', url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800', position: 0, label: 'Frente', created_at: '' },
    ],
    user: { id: 'u5', email: 'lucas@email.com', name: 'Lucas Ferreira', type: 'seller' as const, city: 'São Paulo', state: 'SP', created_at: '', is_pro: true },
    category: { id: '1', name: 'Eletrônicos', icon: '📱', slug: 'eletronicos' },
    distance_km: 7.2,
  },
  {
    id: '6',
    user_id: 'u6',
    title: 'Vestido de Festa Longo Azul Royal',
    description: 'Vestido longo de festa, cor azul royal, tamanho M. Usado apenas uma vez.',
    category_id: '4',
    price: 450,
    condition: 'like_new' as const,
    location_lat: -23.5505,
    location_lng: -46.6333,
    city: 'São Paulo',
    state: 'SP',
    negotiation_radius_km: 20,
    status: 'active' as const,
    allow_resale_by_others: false,
    donation_enabled: true,
    donation_type: 'percentage' as const,
    donation_value: 10,
    charity_id: 'c2',
    auction_enabled: false,
    flash_offer_enabled: false,
    views_count: 78,
    favorites_count: 15,
    regeneration_count: 0,
    created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'i7', product_id: '6', url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', position: 0, label: 'Frente', created_at: '' },
    ],
    user: { id: 'u6', email: 'carla@email.com', name: 'Carla Lima', type: 'seller' as const, city: 'São Paulo', state: 'SP', created_at: '', is_pro: false },
    category: { id: '4', name: 'Roupas', icon: '👕', slug: 'roupas' },
    distance_km: 1.5,
  },
];
