export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// This file will be auto-generated by Supabase CLI
// For now, it serves as a placeholder with the expected structure
export interface Database {
  public: {
    Tables: {
      users: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      admin_users: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      products: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      product_images: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      product_videos: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      categories: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      favorites: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      search_history: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      messages: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      conversations: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      orders: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      payments: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      payment_splits: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      commissions: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      charities: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      donations: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      auctions: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      auction_bids: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      flash_offers: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      reports: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      support_tickets: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      notifications: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      admin_audit_logs: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      // audit_logs: tabela ativa para LGPD/auditoria de acoes de usuario (criada por scripts/create-audit-logs.js).
      // Distinta de admin_audit_logs (schema original, auditoria de acoes de admin).
      // O codigo em src/lib/audit.ts e src/app/admin/audit-logs/page.tsx usa esta tabela.
      audit_logs: {
        Row: {
          id: string;
          actor_id: string;
          actor_email: string | null;
          action: string;
          target_type: string;
          target_id: string | null;
          target_email: string | null;
          details: Record<string, unknown> | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id: string;
          actor_email?: string | null;
          action: string;
          target_type: string;
          target_id?: string | null;
          target_email?: string | null;
          details?: Record<string, unknown> | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          actor_email?: string | null;
          action?: string;
          target_type?: string;
          target_id?: string | null;
          target_email?: string | null;
          details?: Record<string, unknown> | null;
          ip_address?: string | null;
        };
      };
      system_settings: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> };
      user_consents: {
        Row: {
          id: string;
          user_id: string;
          subject: string;
          purpose: string;
          legal_basis: string;
          version: string;
          granted: boolean;
          granted_at: string;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject: string;
          purpose?: string;
          legal_basis?: string;
          version?: string;
          granted: boolean;
          granted_at?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          subject?: string;
          purpose?: string;
          legal_basis?: string;
          version?: string;
          granted?: boolean;
          granted_at?: string;
          source?: string;
          updated_at?: string;
        };
      };
    };
  };
}
